---
title: "RNASeq data analysis "
author: "Reka_Toth"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output:
 # html_notebook: default
  workflowr::wflow_html:
    toc: false
    code_folding: "show"
#output: workflowr::wflow_html:
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(GEOquery)
library(limma)
library(dplyr)
library(edgeR)

```


```{r}
# clear the sample annotation 
data <- getGEO('GSE181144')
metadata <-  data$GSE181144_series_matrix.txt.gz@phenoData@data
phenodata <- metadata[,c("title", "geo_accession", "source_name_ch1", "cell type:ch1", "tissue:ch1", "treatment:ch1", "description", "characteristics_ch1")]


gene_count_matrix <- read.table("data/count_data.txt", header = T, row.names=1)

cat("Filtering the dataset, so only two groups are included - for the sake of simplicity. \n")

phenodata <- phenodata %>%
  filter(grepl("overexpression", description))  %>%
  rename_with(~ gsub(" |:", ".", .x)) %>%
  mutate(description=gsub(" ", "_", description)) %>%
  mutate(description=gsub("overexpression", "oe", description)) 
cat("The correct order has to be given! \n")


gene_count_matrix <- gene_count_matrix[,rownames(phenodata)]

```
## Read data in 

Using edgeR package to read the data and process it. 

```{r}
dge <- DGEList(counts=gene_count_matrix)

design <- model.matrix(data=phenodata, ~ description)

dge <- calcNormFactors(dge)

keep <- filterByExpr(dge, design)
dge <- dge[keep,,keep.lib.sizes=FALSE]
dge <- calcNormFactors(dge)


```

```{r}

v <- voom(dge, design, plot=TRUE)


```



```{r}

pca_res <- prcomp(t(lcpm), scale. = TRUE)
pca_plot <- as.data.frame(cbind(pca_res$x,phenodata))

ggpubr::ggscatter(pca_plot, x="PC1", y="PC2", color="description")

```

## voomLmFit


```{r}


vfit2 <- voomLmFit(dge, design=design, sample.weights=FALSE)
vfit2 <- eBayes(vfit2)
tt <- topTable(vfit2, coef=2, sort.by="P", number=nrow(dge$counts))


```

## Multiple groups

```{r}

phenodata <- phenodata %>% 
  mutate(patient= gsub("(.*)_(empty_vector|MEOX2)_(rep[[:digit:]])", "\\1", title))

design <- model.matrix(data=phenodata, ~ 0+patient)
vfit2 <- voomLmFit(dge, design=design, sample.weights=FALSE)

contr <- makeContrasts(patientL0125 - patientL0512, levels = colnames(coef(vfit2)))


tmp <- contrasts.fit(vfit2, contr)
tmp <- eBayes(tmp)

top.table <- topTable(tmp, sort.by = "P")


```

## Adjustment for confounding factor 

```{r}

design <- model.matrix(data=phenodata, ~0+patient + description) 
vfit2 <- voomLmFit(dge, design=design, sample.weights=TRUE)
vfit2 <- eBayes(vfit2)
tt <- topTable(vfit2, coef=4, sort.by="P", number=nrow(dge$counts))
dt <- decideTests(vfit2)

```

```{r}


cpm <- cpm(dge)
lcpm <- cpm(dge, log=TRUE)

glMDPlot(vfit2, coef=1, status=dt, main=colnames(c)[vfit2],
         side.main="ENTREZID", counts=lcpm, groups=phenodata$group, launch=TRUE)

glimmaMA(vfit2, dge = dge, groups = phenodata$description, coef = 4)

```


```{r}
library(DESeq2)

gene_count_matrix <- gene_count_matrix[rowSums(gene_count_matrix)>10,]


cat("")
#phenodata$description <- factor(phenodata$description, levels=c("oe_control", "MEOX2_oe"))

dds <- DESeqDataSetFromMatrix(countData = gene_count_matrix,
                              colData = phenodata,
                              design = ~ patient + description)

dds <- DESeq(dds)
DEresults = results(dds)
DEresults <- as.data.frame(DEresults)

```

```{r}
gene_anno <- data.frame(row.names = rownames(DEresults), GeneID=rownames(DEresults))
gene_anno$symbol <- mapIds(org.Hs.eg.db,
                            keys=gene_anno$GeneID,
                            column="SYMBOL",
                            keytype="ENTREZID",
                            multiVals="first")
gene_anno$ensembl <- mapIds(org.Hs.eg.db,
                            keys=gene_anno$GeneID,
                            column="ENSEMBL",
                            keytype="ENTREZID",
                            multiVals="first")

```


```{r}
tt <- topTable(vfit2, coef=4, sort.by="P", number=20000)

combined_res <- merge(tt, DEresults, by="row.names", sort=F, all=F, suffixes = c(".limma",".deseq"))

combined_res <- merge(combined_res, gene_anno, by.x="Row.names", by.y="GeneID", sort=F, all=F)

combined_res <- combined_res %>%
  mutate(log10padj_limma=-log10(adj.P.Val), log10padj_deseq=-log10(padj))

ggscatter(combined_res, x="log10padj_limma", y="log10padj_deseq")

```


```{r}



```












```{r}

ge_mat <- getVarianceStabilizedData(dds)

valid_res <- DEresults %>%
  as.data.frame() %>%
  filter(!is.na(padj)) 
  
valid_res <- valid_res[rownames(valid_res) %in% rownames(ge_mat),] %>%
  mutate(log10padj=-log10(padj)) %>%
  cbind(gene_anno[rownames(valid_res),])


#phenodata <- phenodata %>% 
 # rename(group=description)
colnames(phenodata)[7] <- "group"
glMDPlot(
x=valid_res, xval="log2FoldChange", yval="log10padj",
counts = ge_mat[rownames(valid_res),],
anno = gene_anno[rownames(valid_res),],
groups = phenodata[,"group"],
main = "MD plot",
status = as.numeric(valid_res$padj < 0.05),
launch = T,
folder = "/glimma-plots" ,
transform = F, samples = rownames(phenodata), html = "MD_deseq.html"
)

```

##Volcano plot

```{r}
combined_res$sig_limma <- ifelse(combined_res$adj.P.Val<0.05 & abs(combined_res$logFC)>1, "yes", "no")
ggscatter(combined_res, y="log10padj_limma", x="logFC", color="sig_limma", palette=c("black", "red"))

```

##Heatmap of significant genes

```{r}
#Homework :)


```

# Over-representation analysis 


```{r}
library(DOSE)
library(enrichplot)
library(clusterProfiler)



ego <- enrichGO(gene          =combined_res[combined_res$adj.P.Val<0.05 & abs(combined_res$logFC)>0.5,"Row.names"],
                universe      = combined_res$Row.names,
                OrgDb         = org.Hs.eg.db,
                ont           = "BP",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.01,
                qvalueCutoff  = 0.05,
        readable      = TRUE)
barplot(ego, showCategory=20, x="qvalue") 
dotplot(ego, showCategory=20)

ego2 <- pairwise_termsim(ego)
p1 <- treeplot(ego2)

geneList <- combined_res[combined_res$adj.P.Val<0.05,"logFC"]
geneList <- setNames(geneList, nm = combined_res[combined_res$adj.P.Val<0.05,"Row.names"])

 heatplot(ego, foldChange=geneList, showCategory=20)

edo <- enrichDGN(combined_res[combined_res$adj.P.Val<0.05,"Row.names"], universe = combined_res$Row.names)
barplot(edo, showCategory=20)
dotplot(edo, showCategory=20)


edox <- setReadable(edo, 'org.Hs.eg.db', 'ENTREZID')
p1 <- cnetplot(edox, foldChange=valid_res[valid_res$padj<0.05,"log2FoldChange"])
p1
 


```

